baseurl = "https://benzo004.github.io/"
title = "Portfolio"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
publishDir = "docs"

[pagination]
pagerSize = 20

[markup.highlight]
style = "github-dark"

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false
[markup.goldmark.parser.attribute]
block = true
title = true

[markup.goldmark.extensions]
typographer = false

[params]
  author = "Andrii"
  info = "Cybersecurity student"
  description = "Andrii's Portfolio"
  keywords = "blog,developer,personal"
  avatarurl = "/images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"


  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # Remove custom CSS configuration as we'll use the theme's built-in styling
  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

ignoreLogs = ['warning-goldmark-raw-html']

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/benzo004/"
[[params.social]]
  name = "Gitlab"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/andriiz/"
[[params.social]]
  name = "THM"
  icon = "fas fa-user-secret"
  weight = 3
  url = "https://tryhackme.com/r/p/benzo004"  

# Menu links
[[menu.main]]
  name = "Projects"
  weight = 1
  identifier = "posts"
  url = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"